#!/bin/zsh
set -xeuf
[ "x${1:-}" = "x-h" ] && \
	echo "usage: $0 [-h|live]" && \
	echo "   -h      this message" && \
	echo "   live    do it live" && \
	exit 0
# darkice config
CFG=~/binaergewitter_full.cfg
# PREFIX
SM=BGT

if ! pidof jackd; then
	echo "Jackd not running! Bailing out"
	exit 1
fi


LAST=`sed -n "s/name=$SM\(.*\)/\1/p" $CFG | head -1`
NOW=`printf %03d $(($LAST+1))`
if [ "x${1:-}" != "xlive" ]
then 
	echo "this is what your config looks like"
	sed -e "s/$SM$LAST/$SM$NOW/" $CFG
else
	echo "We are doing it live!"
	echo "CURRENT SESSION IS $SM$NOW"
	sed -i "s/$SM$LAST/$SM$NOW/" $CFG

	if pidof darkice; then
		echo "Darkice already running! Bailing out"
		exit 1
	fi
	tmux start-server
	tmux new-session -d -s darkice -n darkice "darkice -c $CFG"
	sleep 2
	for i in `seq 1 6`;do
		jack_connect system:capture_$i darkice:left
		jack_connect system:capture_$i darkice:right
	done
fi
